# Generated by Django 5.1 on 2024-08-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('key_words', models.CharField(blank=True, max_length=255)),
                ('resources', models.CharField(blank=True, max_length=255)),
                ('innovation_type', models.CharField(choices=[('Incremental', 'Incremental'), ('Radical', 'Radical'), ('Transformacional', 'Transformacional'), ('Otro', 'Otro')], default='Tipo de Innovación', max_length=50)),
                ('innovation_focus', models.CharField(choices=[('Modelo de Negocios', 'Modelo de Negocios'), ('Productos', 'Productos'), ('Servicios', 'Servicios')], default='Foco de Innovación', max_length=50)),
                ('created_at', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
            options={
                'verbose_name': 'Ideas',
                'db_table': 'tbl_ideas',
                'ordering': ['title'],
            },
        ),
    ]
